# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10