services:
  db:
    image: mysql:8.2.0-oracle
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  rails_app:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    environment:
      - MYSQL_HOST=db
    command: ash -c "rm -f tmp/pids/unicorn.pid && bundle exec unicorn_rails -c config/unicorn.rb"
    volumes:
      - .:/sample_app_rails7
      - sockets:/sample_app_rails7/tmp/sockets
      - ./public:/sample_app_rails7/public
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - sockets:/sample_app_rails7/tmp/sockets
      - ./public:/sample_app_rails7/public
    depends_on:
      - rails_app
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./serverless:/opt/code/localstack/serverless

volumes:
  sockets:
