version: '3'
services:
  db:
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  rails:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    environment:
      - MYSQL_HOST=db
    command: ash -c "rm -f tmp/pids/unicorn.pid && bundle exec unicorn_rails -c config/unicorn.rb"
    volumes:
      - .:/sample_app_rails7
      - ./tmp/sockets:/sample_app_rails7/tmp/sockets
      - ./public:/sample_app_rails7/public
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/sockets:/sample_app_rails7/tmp/sockets
      - ./public:/sample_app_rails7/public
    depends_on:
      - rails